FROM apache/airflow:3.1.0-python3.12

USER root
RUN apt-get update && apt-get install -y gosu && apt-get clean && rm -rf /var/lib/apt/lists/*
USER airflow

COPY requirements.txt .

RUN pip install -r requirements.txt

RUN pip uninstall dataclasses -y
